version: '3.1'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!!!Root1234"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"